[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fndeutils"
version = "0.0.2"
requires-python = ">=3.9"
dependencies = [
    "discord.py>=2.2.0",
    "pillow"
]

